# This compose file contains everything needed for launching PartMATE locally
version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MARIA_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${PARTKEEPR_DATABASE_NAME}'
      MYSQL_USER: '${PARTKEEPR_DATABASE_USER}'
      MYSQL_PASSWORD: '${PARTKEEPR_DATABASE_PASS}'
    volumes:
      - ${DOCKER_VOLUME_DIR}/mariadb:/var/lib/mysql
    labels:
      - 'traefik.enable=false'
    ports:
      - '3306:3306'
    networks:
      - net
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8081:8080'
    networks:
      - net
  partkeepr:
    image: mhubig/partkeepr:latest
    restart: unless-stopped
    environment:
      PARTKEEPR_DATABASE_HOST: mariadb
      PARTKEEPR_DATABASE_NAME:
      PARTKEEPR_DATABASE_USER:
      PARTKEEPR_DATABASE_PASS:
      PARTKEEPR_SECRET:
    ports:
      - '8080:80'
    volumes:
      - partkeepr_conf:/var/www/html/app/config
      - ${DOCKER_VOLUME_DIR}/partkeepr/data:/var/www/html/data
      - partkeepr_web:/var/www/html/web
    depends_on:
      - mariadb
    networks:
      - net

  partmate:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ${DOCKER_VOLUME_DIR}/partmate/config:/opt/app/config
      - ${DOCKER_VOLUME_DIR}/partkeepr/data:/opt/app/data
    ports:
      - '3000:3000'
    networks:
      - net
    environment:
      PARTMATE_DB_HOST: mariadb
      PARTMATE_DB_USER: '${PARTKEEPR_DATABASE_USER}'
      PARTMATE_DB_PASSWORD: '${PARTKEEPR_DATABASE_PASS}'
      PARTMATE_DB_DATABASE: '${PARTKEEPR_DATABASE_NAME}'
      PARTMATE_HTTP_BASEURL: 'http://localhost:3000'
      PARTMATE_LOG_LEVEL: debug

networks:
  net:
    internal: false

volumes:
  partkeepr_web:
  partkeepr_conf:
