<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/search"></ion-back-button>
        </ion-buttons>
        <ion-title>{{ t("title") }}</ion-title>
        <ion-buttons slot="primary">
          <ion-button @click="scanQRCode()">
            <ion-icon slot="icon-only" :icon="addSharp"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <ion-modal
        :is-open="qrModalIsOpen"
        @onDidDismiss="handleScanCancel"
        keyboard-close
        :initialBreakpoint="0.5"
        :breakpoints="[0.5, 1]"
      >
        <scan-view
          @scanCancel="handleScanCancel"
          @scanResult="handleScanResult"
        ></scan-view>
      </ion-modal>
      <ion-text v-if="!loading && linkList.length == 0">
        {{ t("msg.emptyResult") }}
      </ion-text>
      <ion-list v-if="linkList.length > 0">
        <ion-item-sliding v-for="l in linkList" :key="l.link">
          <ion-item lines="full">
            <ion-icon
              :icon="linkOutline"
              slot="start"
              :color="
                l.link == parentLink
                  ? 'tertiary'
                  : l.autoGenerated
                  ? 'light'
                  : ''
              "
            ></ion-icon>
            <ion-text>{{ l.link }}</ion-text>
          </ion-item>
          <ion-item-options side="end">
            <ion-item-option
              color="danger"
              v-if="linkList.length > 1"
              @click="removeLink(l.link)"
            >
              {{ t("btn.delete") }}
            </ion-item-option>
          </ion-item-options>
        </ion-item-sliding>
      </ion-list>
      <ion-loading :is-open="loading" :message="t('loading')"></ion-loading>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import {
  IonPage,
  IonToolbar,
  IonButtons,
  IonTitle,
  IonHeader,
  IonBackButton,
  IonContent,
  IonButton,
  IonIcon,
  IonLoading,
  IonItemSliding,
  IonItemOption,
  IonItemOptions,
  IonList,
  IonItem,
  IonText,
  IonModal,
  toastController,
} from '@ionic/vue';
import { defineComponent, ref, Ref } from '@vue/runtime-core';
import { addSharp, linkOutline } from 'ionicons/icons';
import { LinkInfo, LinkType } from '@/models/link';
import { createLink, deleteLink, getLinksByParentLink } from '@/api';
import { errorDisplay } from '@/composables/errorDisplay';
import ScanView from '@/components/QRScanner.vue';

export default defineComponent({
  name: 'PartLinkOverview',
  components: {
    IonPage,
    IonToolbar,
    IonButtons,
    IonTitle,
    IonHeader,
    IonBackButton,
    IonContent,
    IonButton,
    IonIcon,
    IonLoading,
    IonItemSliding,
    IonItemOption,
    IonItemOptions,
    IonList,
    IonItem,
    IonText,
    IonModal,
    ScanView,
  },
  props: {
    id: String,
  },
  computed: {
    parentLink() {
      return this.id || this.$route.params.id as string || '';
    }
  },
  methods: {
    async reloadData() {
      if (!this.parentLink) {
        return;
      }
      this.loading = true;
      try {
        this.linkList = await getLinksByParentLink(this.parentLink);
      } catch (err) {
        this.showError(String(err), 'err.load');
      }
      this.loading = false;
    },
    async removeLink(id: string) {
      if (!id) {
        return;
      }
      let newId = id;
      if (id == this.parentLink) {
        const found = this.linkList.find(item => item.link !== id)
        if (found) {
          newId = found.link;
        }
      }
      try {
        await deleteLink(id);
      } catch (err) {
        this.showError(String(err), 'err.load');
      }
      if (newId !== id) {
        // Relocate!
        this.$router.replace(`/link/${newId}/links`);
      } else {
        this.reloadData();
      }
    },
    scanQRCode() {
      this.qrModalIsOpen = true;
    },
    handleScanCancel() {
      this.qrModalIsOpen = false;
    },
    async handleScanResult(link: LinkInfo) {
      this.qrModalIsOpen = false;
      if (link.targetType == LinkType.Unmapped) {
        try {
          await createLink(link.link, this.linkList[0].targetType, this.parentLink)
        } catch (err) {
          this.showError(String(err), 'err.link');
        }
      } else {
        const toast = await toastController.create({
          duration: 2000,
          color: 'danger',
          message: this.t('err.qrCodeAlreadyUsed'),
          position: 'bottom',
        });
        await toast.present();
      }
      this.reloadData();
    },
  },
  mounted() {
    this.$nextTick(function () {
      this.reloadData();
    });
  },
  setup() {
    const { t, dismissError, showError } = errorDisplay();

    const linkList: Ref<Array<LinkInfo>> = ref([]);
    const loading = ref(false);
    const qrModalIsOpen = ref(false);

    return {
      t,
      dismissError,
      showError,
      addSharp,
      linkList,
      loading,
      linkOutline,
      qrModalIsOpen,
    }
  }
});
</script>

<i18n locale="de" lang="yaml">
title: Links
loading: Lade...
msg:
  emptyResult: |
    Dieses Element verfügt über keine Links.
btn:
  delete: Löschen
  dismiss: Schließen
err:
  qrCodeAlreadyUsed: |
    Der gescannte Code wird bereits anderweitig verwendet
  load: Beim Laden der Daten ist ein Fehler aufgetreten
  link: Link konnte nicht erstellt werden
</i18n>
<i18n locale="en" lang="yaml">
title: Links
loading: Loading...
msg:
  emptyResult: |
    This item has no links.
    Click '+' to add some
btn:
  delete: Delete
  dismiss: Dismiss
err:
  qrCodeAlreadyUsed: |
    The code you scanned was already used elsewhere
  load: An error ocurred while loading data
  link: Failed to create link
</i18n>

<style scoped>
.partPreview {
  width: 100%;
  height: auto;
  object-fit: cover;
}

ion-card > ion-item {
  --background: transparent;
}
</style>
