name: build
run-name: Build docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: derwhity/partmate:latest
